### ISSUE TITLE
/elections create does not work.

### ISSUE THREAD

**Issue by EinJOJO** [thomasmny/Elections#34]
Creating an issue for somebody else, thus can not provide more details.
discord of the person: `_sn3akyy`

Exception: https://just-paste.it/0bxI5mi5c8/

Server Version: 
- 1.20 Paper, Purpur 1.20.1 and Paper 1.20.1

Context:
- "All other commands are working"
- "using it for the first time"

**Comment by thomasmny** [comment]
I think I've forgotten to un-exclude `XEnchantment` while shading. Could you pass on the following version to see if it fixes the issue? Thanks

[elections-2.10.7-SNAPSHOT.jar.zip](https://github.com/user-attachments/files/16376735/elections-2.10.7-SNAPSHOT.jar.zip)

**Comment by EinJOJO** [comment]
Ne passt schon.  ;-;
Hätte das sofort fragen sollen :smile: 


![grafik](https://github.com/user-attachments/assets/f8e014d3-2802-4d90-b059-aef946f88d62)

**Comment by thomasmny** [comment]
Na gut, wenns klappt ist's ja super... ändert aber trotzdem nichts daran, dass die Klasse nicht geschadet wurde ¯\_(ツ)_/¯ 
Notfalls soll er die obige Version versuchen
